### ISSUE TITLE
TabError: inconsistent use of tabs and spaces in indentation

### ISSUE THREAD

**Issue by fredottenhof** [Narcolapser/python-o365#42]
I get this error after having installed O365 through pip:

>>> import O365
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    import O365
  File "C:\Users\fredo\AppData\Local\Programs\Python\Python35-32\lib\site-packages\O365\__init__.py", line 23, in <module>
    from .cal import Calendar
  File "C:\Users\fredo\AppData\Local\Programs\Python\Python35-32\lib\site-packages\O365\cal.py", line 7, in <module>
    from O365.event import Event
  File "C:\Users\fredo\AppData\Local\Programs\Python\Python35-32\lib\site-packages\O365\event.py", line 305
    def setStartTimeZone(self,val):
                                  ^
TabError: inconsistent use of tabs and spaces in indentation
>>> 

Please let me know when corrected

Fred Ottenhof

**Comment by Narcolapser** [comment]
Yea. I saw that error. I forgot to check some one's pull request before I merged. I'll tend to it shortly.

**Comment by Narcolapser** [comment]
Fixed it. update to 0.9.2 and you should be good.

**Comment by fredottenhof** [comment]
Now that is speedy !!  Thanks very much !!

I’ll start the update immediately.

Fred.
