### ISSUE TITLE
'value' key error when trying to access mail inbox

### ISSUE THREAD

**Issue by thomascrha** [Narcolapser/python-o365#78]
code to replicate problem - 

```
#!/usr/bin/env python

from O365 import Inbox 

auth = ('user@appen.com','somepassword')

i = Inbox(auth,getNow=False) #Email, Password, Delay fetching so I can change the filters.

i.setFilter("IsRead eq false & Subject eq 'Fetch File'")

i.getMessages()
```

After playing around with the code for a bit I stoped the error but this workflow continues to give me 

```Traceback (most recent call last):
  File "checkemail.py", line 13, in <module>
    i.getMessages()
  File "/Users/tcrha/Appen/appen_text/appenText/venv/lib/python2.7/site-packages/O365/inbox.py", line 56, in getMessages
    for message in response.json()['value']:
KeyError: 'value'
```

As long as you have the correct login for that domain.

**Comment by LudvigGee** [comment]
I get a similar error. Code to replicate the problem:
```
from O365 import Connection, FluentInbox

Connection.oauth2("some-app-id", "some-secret", store_token=True)
inbox = FluentInbox()

for message in inbox.from_folder('test').search('').fetch(count=1):
    print(message.getBody())
```

Error message:
```
File "office-test.py", line 9, in <module>
    print(message.getBody())
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/site-packages/O365/fluent_message.py", line 152, in getBody
    return self.json['Body']['Content']
KeyError: 'Content'
```
